# Generated by Django 4.2.23 on 2025-08-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='info_blocks/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('image_side', models.CharField(choices=[('left', 'Изображение слева'), ('right', 'Изображение справа')], max_length=10, verbose_name='Расположение изображения')),
            ],
            options={
                'verbose_name': 'Блок информации',
                'verbose_name_plural': 'Блоки информации',
                'db_table': 'info_block',
                'ordering': ['order'],
            },
        ),
    ]
