# Generated by Django 4.2.23 on 2025-08-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_infoblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Страница «О Федерации»',
                'verbose_name_plural': 'Страница «О Федерации»',
                'db_table': 'about_page',
            },
        ),
        migrations.AlterModelOptions(
            name='infoblock',
            options={'ordering': ['order'], 'verbose_name': 'Блок подробнее', 'verbose_name_plural': 'Блоки подробнее'},
        ),
    ]
