# Generated by Django 4.2.23 on 2025-11-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='static/tournaments/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Турниры',
                'verbose_name_plural': 'Турниры',
                'db_table': 'tournaments',
            },
        ),
        migrations.AlterField(
            model_name='infoblock',
            name='image',
            field=models.ImageField(upload_to='static/info_blocks/', verbose_name='Изображение'),
        ),
    ]
