# Generated by Django 4.2.23 on 2025-11-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tournaments_alter_infoblock_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoblock',
            name='image',
            field=models.ImageField(upload_to='info_blocks/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='image',
            field=models.ImageField(upload_to='tournaments/', verbose_name='Изображение'),
        ),
    ]
